### ISSUE TITLE
MSAS MENU Release list

### ISSUE THREAD

**Issue by YY7MII** [ThexGameLord/MSAS#2]

**Comment by YY7MII** [comment]
MSAS_MENU v1.0 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.0)

**Comment by ThexGameLord** [comment]
MSAS_MENU v1.1 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.1)

**Comment by ThexGameLord** [comment]
> MSAS_MENU v1.0 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.0)

test

**Comment by YY7MII** [comment]
> MSAS_MENU v1.0 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.0)

MSAS_MENU v1.1 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.1)

**Comment by YY7MII** [comment]
> MSAS_MENU v1.0 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.0)

> MSAS_MENU v1.1 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.1)

>MSAS_MENU v1.2 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.2)

MSAS_MENU v1.3 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.3)

**Comment by ThexGameLord** [comment]
> > > MSAS_MENU v1.0 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.0)
> > 
> > 
> > MSAS_MENU v1.1 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.1)
> 
> MSAS_MENU v1.2 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.2)

MSAS_MENU v1.3 for windows [here](https://github.com/ThexGameLord/MSAS/releases/tag/menu_v1.3)
